## StandardScaler

In [9]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
#### READ & IDENTIFY DATA ####
path = r"D:\SOME_THINGS\Projects\python-examples\Note_Book\Machine_Learning\STANDARD_LINEAR_REGRESSION\test.csv"
data = pd.read_csv(path, header=None, names=["x", "y"])
X=data[["x"]]   # X is the input
y=data[["y"]]   # y is the output
f_data = X
t_data = y
scaler = StandardScaler()

f_data1 = scaler.fit_transform(f_data) 
print("X",f_data1)
t_data1 = scaler.fit_transform(t_data) 
print("y",t_data1)



X [[ 0.71096741]
 [ 1.29179448]
 [ 3.65462727]
 [-0.78222146]
 [-0.43225941]
 [ 0.26368607]
 [-0.61485741]
 [-0.00777664]
 [-0.0804651 ]
 [-0.03793044]
 [-0.68958753]
 [ 1.20279889]
 [-0.49403282]
 [-0.74178082]
 [-0.35553998]
 [ 0.90754295]
 [-0.64577029]
 [-0.10891751]
 [-0.30041507]
 [-0.82991263]
 [-0.63851977]
 [ 0.90544894]
 [-0.70652286]
 [-0.18338587]
 [-0.76774659]
 [-0.2138276 ]
 [-0.16692169]
 [-0.4994249 ]
 [-0.49259318]
 [-0.51476355]
 [-0.68084502]
 [ 0.27991467]
 [ 0.31744987]
 [ 0.15301744]
 [-0.80135551]
 [ 3.41276867]
 [ 1.74514846]
 [ 2.80550468]
 [-0.26766993]
 [ 0.0142105 ]
 [ 0.52224442]
 [-0.71756879]
 [ 3.16724556]
 [ 0.49606924]
 [-0.2372282 ]
 [-0.58491301]
 [-0.26565444]
 [-0.84124647]
 [-0.44312211]
 [-0.18380468]
 [-0.83873366]
 [ 0.53219098]
 [-0.82009694]
 [-0.65741824]
 [-0.79897357]
 [-0.49343079]
 [ 0.39992784]
 [-0.45149816]
 [ 0.07234556]
 [ 0.24588695]
 [-0.58601237]
 [-0.712072  ]
 [-0.83273954]
 [-0.6630459 ]
 [-0.15815301]
 [-0.62038037]
 [-0.768

## MinMaxScaler

In [20]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler() ## MinMaxScaler(copy=True, feature_range=(0, 1))
scaler.fit(data)
newdata = scaler.fit_transform(data)

print(newdata)

### some of attributes
print("range",scaler.data_range_)
print("min",scaler.data_min_)
print("max",scaler.data_max_)
### some of attributes

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
range [ 2. 16.]
min [-1.  2.]
max [ 1. 18.]


## Normalizer RAWS

In [32]:
from sklearn.preprocessing import Normalizer
X = [[4, 1, 2, 2], 
     [1, 3, 9, 3], 
     [5, 7, 5, 1]]


transformer1 = Normalizer(norm='l1' )

transformer2 = Normalizer(norm='l2' )

transformer3 = Normalizer(norm='max' )

N1=transformer1.fit_transform(X)
N2=transformer2.fit_transform(X)
N3=transformer3.fit_transform(X)


print("N1\n",N1)
print("N2\n",N2)
print("N3\n",N3)

N1
 [[0.44444444 0.11111111 0.22222222 0.22222222]
 [0.0625     0.1875     0.5625     0.1875    ]
 [0.27777778 0.38888889 0.27777778 0.05555556]]
N2
 [[0.8 0.2 0.4 0.4]
 [0.1 0.3 0.9 0.3]
 [0.5 0.7 0.5 0.1]]
N3
 [[1.         0.25       0.5        0.5       ]
 [0.11111111 0.33333333 1.         0.33333333]
 [0.71428571 1.         0.71428571 0.14285714]]


## MaxAbsScaler COLUMNS

In [31]:
## similar of normalizer(max) but in column
from sklearn.preprocessing import MaxAbsScaler
X = [[ 1., 10., 2.],
     [ 2., 0., 0.],
     [ 5., 1., -1.]]
transformer = MaxAbsScaler().fit_transform(X)
print("transformer : \n",transformer)

transformer : 
 [[ 0.2  1.   1. ]
 [ 0.4  0.   0. ]
 [ 1.   0.1 -0.5]]


## FunctionTransformer

In [42]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

X = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

def function1(z):
    return np.divide(z,1000)

FT = FunctionTransformer(func = function1)

print("out\n",FT.fit_transform(X))

out
 [[0.004 0.001 0.002 0.002]
 [0.001 0.003 0.009 0.003]
 [0.005 0.007 0.005 0.001]]


## Binarizer

In [50]:
#بيحول القيم كلها ال اقل من الرقم ال انت مديه له لصفر والاكبر منه لواحد 
from sklearn.preprocessing import Binarizer
X = [[ 1., -1., -2.],
      [ 2., 0., -1.], 
      [ 0., 1., -1.]]

transformer = Binarizer(threshold=0.5 ) 
transformer1 = transformer.fit_transform(X)
print("transformer : \n",transformer1)

transformer : 
 [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


## PolynomialFeatures

In [62]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)
print("Original \n",X)
poly = PolynomialFeatures(degree=2 , include_bias = True)

print("\ninteraction_only=False\n",poly.fit_transform(X))


poly = PolynomialFeatures(interaction_only=True)#here only add columns bais and first*second

print("\ninteraction_only=True\n",poly.fit_transform(X))

Original 
 [[0 1]
 [2 3]
 [4 5]]

interaction_only=False
 [[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]

interaction_only=True
 [[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]
